#Settings
MODE = "Joystick"
INVERT = False
ROTATED = True
DIFFERENTIAL = False
ROLLER_MOTOR_EJECT_SPEED = 0.9
MOVE_SPEED = 1
INVERT_EJECT = False
INVERT_ARM = False

#Axis Mappings
LEFT_JOYSTICK_X_AXIS = 0
LEFT_JOYSTICK_Y_AXIS = 1
LEFT_TRIGGER_AXIS = 2
RIGHT_TRIGGER_AXIS = 3
RIGHT_JOYSTICK_Y_AXIS = 5

#Button Mappings
LB = 5
RB = 6
START = 8

#Key Mappings
W = "w"
A = "a"
S = "s"
D = "d"

#Constants
DRIVER_CONTROLLER_PORT = 0
LEFT_LEADER_ID = 1
LEFT_FOLLOWER_ID = 3
RIGHT_LEADER_ID = 2
RIGHT_FOLLOWER_ID = 4
ROLLER_MOTOR_ID = 5
SERVO_CHANNEL = 0

OPERATOR_CONTROLLER_PORT = 1
DRIVE_MOTOR_CURRENT_LIMIT = 60
ROLLER_MOTOR_CURRENT_LIMIT = 60
ROLLER_MOTOR_VCOMP = 10